

@startuml A1

title Atividade 1 - Diagrama de Classe - Venda de Ingresso de Cinema

    class Cliente{

    + construtor()
    + consultaCliente()
}

class Cinema{

    + construtor()
    + consultaCinema()
}

class Filme{
    
    + construtor()
    + consultaFilme()
}

class Ingresso{

    + construtor()
    + consultaIngresso()
}


@enduml