
@startuml A1

title Atividade 1 - Diagrama de Classe - Venda de Ingresso de Cinema


    class Cliente{
    - idCliente: Int
    - nomeCliente: String
    - senhaCliente: String 
    - enderecoCliente: String
    - emailCliente: String
    + construtor(idCliente, nomeCliente, senhaCliente, enderecoCliente, emailCliente)
    + consultaCliente(idCliente, nomeCliente)
}

class Cinema{

    + construtor()
    + consultaCinema()
}

class Filme{
    - idFilme: String
    - nomeFilme: String
    - descricao: String
}

class Ingresso{

    + construtor()
    + consultaIngresso()
}


@enduml
